version: '3.3'
services:

    mariadb:
        image: mariadb:10.2
        container_name: container-mariadb-php
        environment: 
            - MYSQL_ROOT_PASSWORD=root

    php:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: container-php
        volumes:
            - ./php:/var/www/html/
        ports:
            - "8083:80"
        links:
            - mariadb:db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.6
        container_name: container-phpmyadmin-php
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "8035:80"
        links:
            - mariadb:db
